import { Subject, Student, ClassStream, Score, Teacher } from './model';


export const HEROES: Subject[] = [
  { id: 11, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
    modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 12, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
    modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 13, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 14, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 15, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 16, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 17, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 18, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 19,modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'},
  { id: 20, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), name: 'Agriculture',
  modified_by: 'JIMMY', created_by: 'jimmy' , description: 'Science'}
];


export const STUDENTS: Student[] = [
    { id: 1, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 2, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 3, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 4, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 5, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 6, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 7, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 8, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'},
    { id: 9, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Agriculture',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', student_admission_no: 'JCH002'}
  ];
  

  export const TEACHERS: Teacher[] = [
    { id: 1, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Agriculture', otherName: 'Agriculture', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 2, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 3, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 4, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 5, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 6, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 7, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 8, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'},
    { id: 9, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  firstName: 'Teacher',
    lastName: 'Teacher', otherName: 'Teacher', gender: 'Male', teacher_number: 'TSC-021'}
  ];

  export const CLASSES: ClassStream[] = [
    { id: 1, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy',  className: 'Teacher',
    classGrade: 'Agriculture',  description: 'TSC-021'},
    { id: 2, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 3, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 4, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 5, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 6, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 7, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 8, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'},
    { id: 9, modified_on: new Date("2019-01-16"), created_on: new Date("2019-01-16"), 
    modified_by: 'JIMMY', created_by: 'jimmy', students: {}, className: 'Class A', classGrade: '4',  description: 'TSC-021'}
  ];
